spring:
 datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/db_accomodation
     username: root
     password: toor
 jpa: # JPA
    database_platform: org.hibernate.dialect.MySQLDialect
    openInView: true
    show-sql: false
    database: mysql
    hibernate.ddl-auto: update
 view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
error:
  whitelabel:
    enabled: true

logging:
  level:
    com.wladek.accomodation: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR

